### ISSUE TITLE
Basic front-end functionality

### ISSUE THREAD

**Issue by g33kidd** [g33kidd/bracket#13]
User should be able to:
- View their profile
- Login/Register
- Create a team
- Manage team
- View team profile
- Invite users to team/guild whatever you wanna call it

**Comment by ghost** [comment]
@g33kidd - If your not looking for a React frontend I can help with this. Happy to keep them all in a single issue or want to break then into smaller pieces?

**Comment by g33kidd** [comment]
@adnnn Go for it! Currently I'm just using React for the Admin, but you should be able to do just about anything with the main front-end of the site. Not too much data at the moment besides what's there already, but you could either use the Blade templates or use the API along with that.

Today I'll be adding some more helpers and data things for the front-end.

**Comment by ghost** [comment]
I'll make a start at the weekend most likely, got a few pieces to wrap up at work over the next few days. Did you decide against the TeamWork package when you closed this issue #14 - I'd probably recommend writing the code from scratch and will do if we're on the same page.

**Comment by g33kidd** [comment]
I went with the Teamwork package for now, but the plan is to replace all of that with something built from scratch.

**Comment by g33kidd** [comment]
Just started working on a Team thing. #20

**Comment by g33kidd** [comment]
Closing for now look at #24
